### ISSUE TITLE
Importing apitools.base.py takes half a second

### ISSUE THREAD

**Issue by dhermes** [google/apitools#14]
This makes using the library a very jarring experience for application start-up times.

**Comment by dhermes** [comment]
As mentioned in GoogleCloudPlatform/gcloud-python#755, I did some [timing][1] and here is what I found (with a fresh environment for each import)

```
==================
base_api: 0.602942
---- Imports: ----
    from apitools.base.py import credentials_lib
    from apitools.base.py import encoding
    from apitools.base.py import exceptions
    from apitools.base.py import http_wrapper
    from apitools.base.py import util
==================
batch: 0.607329
---- Imports: ----
    from apitools.base.py import exceptions
    from apitools.base.py import http_wrapper
==================
credentials_lib: 0.603045
---- Imports: ----
    from apitools.base.py import exceptions
    from apitools.base.py import util
==================
encoding: 0.60089
---- Imports: ----
    from apitools.base.py import exceptions
==================
exceptions: 0.604245
---- Imports: ----
==================
extra_types: 0.606001
---- Imports: ----
    from apitools.base.py import encoding
    from apitools.base.py import exceptions
    from apitools.base.py import util
==================
http_wrapper: 0.594856
---- Imports: ----
    from apitools.base.py import exceptions
    from apitools.base.py import util
==================
list_pager: 0.626663
---- Imports: ----
==================
transfer: 0.623979
---- Imports: ----
    from apitools.base.py import buffered_stream
    from apitools.base.py import exceptions
    from apitools.base.py import http_wrapper
    from apitools.base.py import stream_slice
    from apitools.base.py import util
==================
util: 0.629429
---- Imports: ----
    from apitools.base.py import encoding
    from apitools.base.py import exceptions
==================
```

[1]: https://gist.github.com/dhermes/bb10e2db5a0c4eeb2de6

**Comment by dhermes** [comment]
From the above, it seems like `exceptions` is the culprit, but `list_pager` also takes very long without ever importing any other `apitools` modules.

**Comment by dhermes** [comment]
After analysis, it comes from `oauth2client` in `credentials_lib`. My guess is that it is caused by the GCE check, but I'll need to verify.

**Comment by dhermes** [comment]
Relevant issue: pyca/pyopenssl#137

**Comment by craigcitro** [comment]
yucks. thanks for tracking this down.

i think the sanest move is to just wait for this to get fixed in `oauth2client`. (or depend on an old version of `PyOpenSSL`.)

on the flipside, `PyOpenSSL` isn't a required dependency -- installing without it works fine, until you try to use the old `p12` file for a service account.

**Comment by dhermes** [comment]
Yeah I was able to address it with a 3 line change to `oauth2client` (referenced above).

**Comment by dhermes** [comment]
OK so at this point this is just release blocked on being fixed

**Comment by craigcitro** [comment]
done!

or do you also need an oauth2client release?

**Comment by dhermes** [comment]
It isn't urgent. 0.5 seconds sucks, but it's just a startup cost.

However, closing this out shouldn't happen until `oauth2client>1.4.7` (idea for a GitHub add-on, a PyPI trigger)

**Comment by craigcitro** [comment]
should be good now, thanks to your `oauth2client` cleanups.

**Comment by dhermes** [comment]
Yup. And the hack will be able to be removed once `cryptography==1.0` comes out ([source][1]).

[1]: https://github.com/pyca/pyopenssl/issues/137#issuecomment-118911365
