### ISSUE TITLE
Migration path to one-true source is unknown

### ISSUE THREAD

**Issue by dhermes** [google/apitools#16]
There are copies floating here, in https://github.com/craigcitro/apitools, "internal" in Google, in `gsutil` and possible elsewhere.

Is there a migration plan in place? Is there a known set of features that differ? Is there a TODO list?

----

**Most importantly**: Can we (open source peoplez) help?

**Comment by craigcitro** [comment]
actually, this is now the one true copy of the source:
 * craigcitro/apitools is a fork,
 * internal is a mirror of this code,
 * gsutil uses this repo as a submodule, and
 * there are no other forks I created.

there are still some additional internal bits that add internal-only functionality, and a bunch of integration tests. but for the source itself, this is the truth.

as to helping: once i get some cycles, i'm planning to push the integration tests into this repo, and i'll need to set up travis to run them. i totally want to copy the gcloud-python setup for that.

**Comment by dhermes** [comment]
w00t

So I'd say "close this", though I believe you've mentioned elsewhere that you are missing tests here that you run elsewhere.

Maybe close this and file a bug for that? Or just rename here?

**Comment by craigcitro** [comment]
i opened #17 for the tests.
