### ISSUE TITLE
Python 3 support in apitools

### ISSUE THREAD

**Issue by aaltay** [google/apitools#160]
httplib2 is the only blocking dependency for this (https://caniusepython3.com/project/google-apitools) and it has a newer version that supports python3. Are there anything else blocking this feature? Is it possible to get it on the roadmap?

**Comment by craigcitro** [comment]
We already run all our tests under python3 -- is something not working for you?

**Comment by aaltay** [comment]
We have not tested, because `httplib2` was listed as a blocker in the above link I shared. The latests version of httplib2 supports python3 according to the same thing. Is it possible that `'httplib2>=0.8'` requirement potentially pulls an older version of `httplib2` that does not support python3?

**Comment by craigcitro** [comment]
`httplib2>=0.8` will pull the newest available version, as long as it's at least 0.8.

I would try it and report back; I suspect this all Just Works.
