### ISSUE TITLE
Version 0.5.18 reads entire upload streams into memory, which will fail for files larger than available amount of memory 

### ISSUE THREAD

**Issue by houglum** [google/apitools#192]
https://github.com/google/apitools/commit/7ccade5be76c6715c0b8d2109ef6b484edadfe97 added code that calls `read()` on a StreamSlice, thus effectively reading the entire contents of a stream into memory.  This takes away one of the main advantages of using streams - being able to read them gradually and buffer their contents into memory, allowing the transfer of large files.  If you attempt uploads of files larger than the available amount of memory you have, this will fail.

**Comment by kevinli7** [comment]
This is fixed in v0.5.19.
