### ISSUE TITLE
Python 3.3 Travis tests always fail

### ISSUE THREAD

**Issue by HarrisonGregg** [google/apitools#235]
https://travis-ci.org/google/apitools/jobs/392809585

Looks like wheel stopped supporting Python 3.3:
```
wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
```
I'm not sure if there's a workaround, or if apitools should just stop supporting Python 3.3 as well.

**Comment by houglum** [comment]
Sorry for the delay in looking at this -- I dropped Py3.3 support in Travis in https://github.com/google/apitools/commit/e4e56e352c19204a1a39163b9ee5013457eb1c0e.
