### ISSUE TITLE
Upload.RefreshResumableUploadState seeks to beginning of stream on OK, CREATED

### ISSUE THREAD

**Issue by udim** [google/apitools#257]
If the upload has total_size=None, it will seek(0), which breaks our stream implementation (which can only seek to its current position).
Seems like it should be seeking to `self.__GetLastByte(range_header) + 1` in this case.

This is the branch in question: https://github.com/google/apitools/blob/8e836fe2942e74d4f6ae5d4b3ccbaf161b9c052b/apitools/base/py/transfer.py#L836-L844

Stacktrace:
```
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/sdks/python/apache_beam/io/gcp/gcsio.py", line 583, in _start_upload
16:01:43     self._client.objects.Insert(self._insert_request, upload=self._upload)
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/sdks/python/apache_beam/io/gcp/internal/clients/storage/storage_v1_client.py", line 1154, in Insert
16:01:43     upload=upload, upload_config=upload_config)
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/build/gradleenv/1327086738/local/lib/python2.7/site-packages/apitools/base/py/base_api.py", line 715, in _RunMethod
16:01:43     http_request, client=self.client)
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/build/gradleenv/1327086738/local/lib/python2.7/site-packages/apitools/base/py/transfer.py", line 885, in InitializeUpload
16:01:43     return self.StreamInChunks()
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/build/gradleenv/1327086738/local/lib/python2.7/site-packages/apitools/base/py/transfer.py", line 997, in StreamInChunks
16:01:43     additional_headers=additional_headers)
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/build/gradleenv/1327086738/local/lib/python2.7/site-packages/apitools/base/py/transfer.py", line 948, in __StreamMedia
16:01:43     self.RefreshResumableUploadState()
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/build/gradleenv/1327086738/local/lib/python2.7/site-packages/apitools/base/py/transfer.py", line 850, in RefreshResumableUploadState
16:01:43     self.stream.seek(self.progress)
16:01:43   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify/src/sdks/python/apache_beam/io/filesystemio.py", line 269, in seek
16:01:43     offset, whence, self.position, self.last_position))
16:01:43 NotImplementedError: offset: 0, whence: 0, position: 48944, last: 0
```
(https://builds.apache.org/view/A-D/view/Beam/view/All/job/beam_PostCommit_Python_Verify/7444/consoleFull)

Apache Beam issue: https://issues.apache.org/jira/browse/BEAM-6380

**Comment by chamikaramj** [comment]
Hi, any updates on this ?

Some Dataflow customers have run into this.

**Comment by jameslynnwu** [comment]
I don't believe updating that line would help. The stack trace indicates
the seek call in question happened on line 850, which means `range_header`
is None.

Please let me know if there's another fix that we should make to apitools
for this. Something does look off if the refresh_response is
RESUME_IMCOMPLETE but doesn't give us any more information in the
range_header.

James Wu

541-981-0305

**Comment by udim** [comment]
You're right James, I was looking at the wrong branch.

We upload using the RESUMABLE_UPLOAD strategy and total_size=None. The data written to GCS doesn't fit into memory and is generated on-the-fly, hence seeking is infeasible.
https://github.com/apache/beam/blob/47d44b181999b4f1c7d3caa29dc3fd8c98c02dc7/sdks/python/apache_beam/io/gcp/gcsio.py#L559-L563

I guess the question is why range_header is None? When does this happen and is this normal (can we expect it to regularly happen)?

**Comment by udim** [comment]
Also interesting reference:
https://developers.google.com/gdata/docs/resumable_upload#Resuming

Perhaps the range header is missing only for the first chunk. In that case we might be able to cache the last chunk.

**Comment by udim** [comment]
Writing a workaround to allow partial rewinding of stream: https://github.com/apache/beam/pull/8661

**Comment by jameslynnwu** [comment]
udim@, IIUC, this resolves this issue? Please reopen if there is an apitools change that should happen._

**Comment by udim** [comment]
Yes, our workaround seems to be working.
