### ISSUE TITLE
Pull change into `google-cloud-sdk`

### ISSUE THREAD

**Issue by dhermes** [google/apitools#38]
@thobrla I filed:
https://code.google.com/p/google-cloud-sdk/issues/detail?id=165

How does one pull such a change into `google-cloud-sdk`?

**Comment by craigcitro** [comment]
@markpell knows all things gcloud. :grin:

**Comment by markpell** [comment]
Commented on the issue.  We currently do not have a public repo for the gcloud source, but that is something we are working on.

**Comment by dhermes** [comment]
Thanks.
