### ISSUE TITLE
Drop apputils and gflags.

### ISSUE THREAD

**Issue by craigcitro** [google/apitools#8]
We need to drop these two dependencies.

These two libraries get used in two places:
- `gen_client` uses them for processing command-line args 
- generated CLIs use them.

I'll probably take care of this in two steps.

**Comment by vapier** [comment]
any update ?  google-apputils is deprecated and they're closing things as "switch to absl-py".

this is holding back Python 3 migration as google-apputils doesn't work w/py3.

**Comment by craigcitro** [comment]
apputils hasn't been a core dependency of this lib in ages: it's only need to use the generated CLIs. (note that the tests have been passing in python3 for a while.)

is there an example of something specific failing under python3?

**Comment by vapier** [comment]
google-apputils is listed in setup.py still

**Comment by craigcitro** [comment]
Only in the extras, though -- so you can install this just fine in python3, it's only if you try to install `google-apitools[testing]` or `google-apitools[cli]` that you run into that dep.

(You're right that it should probably be removed, but I don't think it should be blocking anything.)

**Comment by vapier** [comment]
in other words, we can't run the tests in distros right ?
